import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google"; // Closest OS match to Google Sans
import "./globals.css";
import { cn } from "@/lib/utils";

const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "DayZero",
  description: "Generated by maintain consistency.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased text-foreground selection:bg-primary/10 overflow-x-hidden pattern-diagonal-lines",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
